trigger:
- main  # Replace with your branch name

pool:
  name: Default  # Use your registered agent pool

jobs:
- job: firstJob
  pool:
    vmImage: 'windows-latest'


      - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    
    - script: |
        choco install chromedriver --version=<latest version>
        choco install googlechrome
      displayName: 'Install dependencies'
    
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'  # Path to your pom.xml file
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to test results

    - script: |
        mvn test
      displayName: 'Run tests'

- job: secondJob
  dependsOn: firstJob
  pool:
    vmImage: 'ubuntu-latest'

 
    
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - script: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y chromium-browser
      displayName: 'Install dependencies'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'  # Path to your pom.xml file
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to test results

    - script: |
        mvn test
      displayName: 'Run tests'


